export const pathDefault = {
  homePage: "/",
  aboutUs: "/pages/about-us",
  contact: "/pages/contact",
  cart: "/cart",
  paymentResult: "payment-result",
  categories: "/categories/:id",
  search: "/search",
  product: "product/:id",
  login: "/login",
  register: "/register",
  account: "/account",
  admin: "/admin",
  managerUser: "/admin/user",
  managerProduct: "/admin/product",
  managerPostProduct: "/admin/product/post",
  managerProductType: "/admin/product-types",
  managerOrder: "/admin/order",
};
